const Employees = [
    {
        id: 1,
        firstname: "Michael",
        lastname: "Rods",
        department: "Information Technology",
        position: "Director",
        salary: "$50000",
      },
      {
        id: 2,
        firstname: "Minerva",
        lastname: "Mitchels",
        department: "Human Resources",
        position: "Clerk",
        salary: "$60000",
      },
      {
        id: 3,
        firstname: "Robert",
        lastname: "Downey",
        department: "Public Relations",
        position: "Editor",
        salary: "$70000",
      },
      { id: 4, firstname: "Mark", lastname: "Hammill", department: "Marketing", position: "Assitant", salary: "$55000" },
      {
        id: 5,
        firstname: "Rei",
        lastname: "Ayanami",
        department: "Information Technology",
        position: "Systems Admin",
        salary: "$40000",
      },
      {
        id: 6,
        firstname: "Laura",
        lastname: "Greenwood",
        department: "Public Relations",
        position: "Manager",
        salary: "$70000",
      },
      {
        id: 7,
        firstname: "Jenn",
        lastname: "Mylan",
        department: "Public Relations",
        position: "Secretary",
        salary: "$80000",
      },
      {
        id: 8,
        firstname: "Charles",
        lastname: "Woods",
        department: "Marketing",
        position: "Photographer",
        salary: "$30000",
      },
      {
        id: 9,
        firstname: "Will",
        lastname: "Reed",
        department: "Human Resources",
        position: "Contractor",
        salary: "$45000",
      },
      {
        id: 10,
        firstname: "Miles",
        lastname: "Cruz",
        department: "Public Relations",
        position: "Editor",
        salary: "$50000",
      },
      {
        id: 11,
        firstname: "Evan",
        lastname: "You",
        department: "Information Technology",
        position: "Programmer",
        salary: "$90000",
      },
      {
        id: 12,
        firstname: "John",
        lastname: "Meyers",
        department: "Information Technology",
        position: "Consultant",
        salary: "$90000",
      },
]

module.exports = {
    Employees
}